name: release library

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Build & Publish nestjs-novaposhta
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build:packages

      - name: Verify npm package version availability
        id: check_version
        run: |
          VERSION=$(jq -r '.version' packages/nestjs-novaposhta/package.json)
          echo "Current package version: $VERSION"

          if npm view nestjs-novaposhta@$VERSION version > /dev/null 2>&1; then
            echo "Version $VERSION already exists on npm. Skipping publish."
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "Version $VERSION does not exist. Will publish."
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish package
        if: steps.check_version.outputs.should_publish == 'true'
        working-directory: packages/nestjs-novaposhta
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}